<?php
    include "includes/navigation.php";
 ?>
        <!--This is the page content-->
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 well">
                        <a href=""><img height="300" width="100%" src="images/LOGO2.png" alt="LOGO"></a>  
                    </div>

                <!-- Main page content-->
                <div class="col-lg-8 well">
                        <h1 class="page-header">
                        Automata
                        <small></small>
                        </h1>
                        <div class="col-md-12">
                            <p>
                            Automata Theory is an exciting, theoretical branch of 
                            computer science. It established its roots during the 
                            20th Century, as mathematicians began developing - both 
                            theoretically and literally - machines which imitated 
                            certain features of man, completing calculations more 
                            quickly and reliably. The word automaton itself, closely 
                            related to the word "automation", denotes automatic 
                            processes carrying out the production of specific processes.
                            Simply stated, automata theory deals with the logic of 
                            computation with respect to simple machines, referred to 
                            as automata. Through automata, computer scientists are able
                            to understand how machines compute functions and solve 
                            problems and more importantly, what it means for a function 
                            to be defined as computable or for a question to be described
                             as decidable .


                            </p> 
                            <h2>Syllabus Of Automata</h2>
                            <ul>
                                <li>Determinstic Finite Automata</li>
                                <li>Non-Deterministic Finite Automata</li>
                                <li>NFA to DFA Conversion</li>
                                <li>DFA Minimization</li>
                                <li>Moore and Melay Machines</li>
                                <li>Languages generated by Grammars</li>
                                <li>Chomsky Normal Form</li>
                                <li>Regular Expression</li>
                                <li>Arden's Theorem</li>
                                <li>Construction of FA from RE</li>
                                <li>Pumping Lemma for Regular Grammar</li>
                                <li>Context Free Grammar</li>
                                <li>Ambiguity in Grammar</li>
                                <li>Greibach Normal Form</li>
                                <li>Pumping Lemm for CFG</li>
                                <li>Turing Machines</li>
                            </ul>
                            <button class="btn btn-success" onclick="location.href='users/register.php';" style="width:20%;">Register</button>
                            <button class="btn btn-primary" onclick="location.href='users/login.php';" style="float:right; width:20%;">Login</button>
                                                    
                        </div>
                    </div>
                     <!-- This is the sidebar section-->
                <?php include "includes/sidebar.php"; ?>

                </div>
            </div>
        <!--This is the footer-->
        <?php include "includes/footer.php";?>